version: "3"
services:
    path-traversal-101:
        build: .
        ports:
            - "10001:3000"
        restart: always
        tty: true
        stdin_open: true
        environment:
            - FLAG=ping{FAKE}
